version: "3.8"

services:
  mysql:
    image: martinstiben/sgh-mysql:1.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: horarios
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my_network

  backend:
    image: martinstiben/sgh-backend:1.0
    container_name: springboot_app
    ports:
      - "8085:8085"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JAVA_OPTS=-Xms512m -Xmx1024m
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/horarios
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=userpass
    depends_on:
      - mysql
    networks:
      - my_network
    restart: always

  frontend-web:
    image: martinstiben/sgh-frontend-web:1.0
    container_name: nextjs_app
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8085
    depends_on:
      - backend
    networks:
      - my_network
    restart: always

  frontend-movil:
    image: martinstiben/sgh-frontend-movil:1.0
    container_name: expo_app
    ports:
      - "19006:19006"
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
    networks:
      - my_network
    restart: always

volumes:
  mysql_data:

networks:
  my_network: