version: "3.8"

services:
  mysql:
    image: mysql
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: horarios
      MYSQL_USER: user
      MYSQL_PASSWORD: 
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my_network

  app:
    container_name: springboot_app
    build:
      context: ./Backend/SGH
      dockerfile: Dockerfile
    image: mi-springboot-app:1.0
    ports:
      - "8085:8085"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JAVA_OPTS=-Xms512m -Xmx1024m
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/horarios
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=userpass
    depends_on:
      - mysql
    networks:
      - my_network
    restart: always

volumes:
  mysql_data:

networks:
  my_network:
